version: '3.7'

services:
  bot:
    image: python:3.7
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "32500:8000"
    command: ["sh", "-c", "ls -laF && pip install -r requirements.txt && gunicorn -w 4 -b 0.0.0.0:8000 oliver.app:app"]
