version: 2.0
jobs:
  build:
    docker:
      - image: ../.
    steps:
      - checkout
      - run:
          name: "Docker_python"
          command: |
            docker-compose up -d --build
      - run:
          name: Check current version of node
          command: node -v

